apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sourish
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
    namespace: sourish
      labels:
        app: frontend
    spec:
      containers:
      - name: react-frontend
        image: democldacr.azurecr.io/darkskullkubefullstackappfront:latest
        imagePullPolicy: 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: sourish
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
