apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  namespace: sourish
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
